sudo: required
servicees:
    - docker

before_install:
    - docker build -t tomerraanan1/try2 -f Dockerfile.dev .

scripts:
    - docker run -e CI=true tomerraanan1/try2 npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-069457654019"
    bucket_path: "docker"
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    on:
        branch: master
